// tests/performance/k6/scenarios/campaign/campaign.js
//
// options is generated by scripts/pg/campaign.py from the selected campaign
// descriptor and passed in as CAMPAIGN_JSON — this file does not hand-author
// scenario weights, executors, or thresholds.
import { catalogBrowse } from "./catalog-browse.js";
import { orderLookup } from "./order-lookup.js";
import { purchase } from "./purchase.js";

export const options = JSON.parse(__ENV.CAMPAIGN_JSON);

export { catalogBrowse, orderLookup, purchase };

// handleSummary rather than --summary-export: the report must carry the run's
// identity (runId + catalogVersion, RUN-004) alongside k6's own metrics, and
// --summary-export can only write k6's data. Defining handleSummary also
// disables --summary-export, so scripts/pg/campaign.py no longer passes it.
export function handleSummary(data) {
  const runId = __ENV.RUN_ID || "local";
  const enriched = {
    runId,
    catalogVersion: __ENV.CATALOG_VERSION ? Number(__ENV.CATALOG_VERSION) : null,
    ...data,
  };
  return {
    // Defining handleSummary suppresses k6's default terminal summary, so a
    // compact one is rebuilt here — no jslib import, which would make the run
    // depend on network access from inside the container.
    stdout: compactSummary(enriched),
    [`/scripts/reports/campaign-${runId}-summary.json`]: JSON.stringify(enriched, null, 2),
  };
}

function compactSummary(enriched) {
  const metrics = enriched.metrics || {};
  const lines = [
    "",
    `campaign ${enriched.runId} (catalogVersion ${enriched.catalogVersion})`,
  ];
  for (const [name, metric] of Object.entries(metrics)) {
    const values = metric && metric.values ? metric.values : {};
    const parts = Object.entries(values)
      .filter(([key]) => ["count", "rate", "avg", "p(95)"].includes(key))
      .map(([key, value]) => `${key}=${typeof value === "number" ? value.toFixed(4) : value}`);
    if (parts.length > 0) lines.push(`  ${name}: ${parts.join(" ")}`);
  }
  return `${lines.join("\n")}\n`;
}
