// tests/performance/k6/scenarios/campaign/campaign.js
//
// options is generated by scripts/pg/campaign.py from the selected campaign
// descriptor and passed in as CAMPAIGN_JSON — this file does not hand-author
// scenario weights, executors, or thresholds.
import { catalogBrowse } from "./catalog-browse.js";
import { orderLookup } from "./order-lookup.js";
import { purchase } from "./purchase.js";

export const options = JSON.parse(__ENV.CAMPAIGN_JSON);

export { catalogBrowse, orderLookup, purchase };
