// options is generated by scripts/pg/campaign.py from the selected campaign
// descriptor and passed in as CAMPAIGN_JSON — this file does not hand-author
// scenario weights, executors, or thresholds.
import { catalogBrowse } from "./catalog-browse";
import { orderLookup } from "./order-lookup";
import { purchase } from "./purchase";
import { buildHtml, buildSummaryJson } from "../../support/report";
import { url } from "../../config/env";

export const options = JSON.parse(__ENV.CAMPAIGN_JSON as string);

export { catalogBrowse, orderLookup, purchase };

// handleSummary rather than --summary-export: the report must carry the run's
// identity (runId + catalogVersion, RUN-004) alongside metrics, and
// --summary-export can only write k6's own data. Defining handleSummary also
// disables --summary-export, so scripts/pg/campaign.py doesn't pass it.
//
// punch's buildSummaryJson gives a generic, consistent summary shape shared
// with every other migrated scenario; it has no concept of runId/
// catalogVersion or per-use-case breakdown, so those are layered on top
// rather than replacing it.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function handleSummary(data: any) {
  const runId = (__ENV.RUN_ID as string) || "local";
  const meta = { title: `Campaign ${runId}`, testType: "campaign", targetUrl: url("") };
  const enriched = {
    runId,
    catalogVersion: __ENV.CATALOG_VERSION ? Number(__ENV.CATALOG_VERSION) : null,
    ...buildSummaryJson(data, meta),
    metrics: data.metrics,
  };
  return {
    stdout: `campaign ${runId}: ${enriched.passed ? "PASS" : "FAIL"} — ${enriched.totalRequests} reqs, ${(enriched.errorRate * 100).toFixed(2)}% failed, p90 ${enriched.p90Ms.toFixed(1)}ms, checks ${(enriched.checkPassRate * 100).toFixed(1)}%\n`,
    [`/scripts/reports/campaign-${runId}-report.html`]: buildHtml(data, meta),
    [`/scripts/reports/campaign-${runId}-summary.json`]: JSON.stringify(enriched, null, 2),
  };
}
